import avatar from "../../src/assets/avatar.png";

export const USERS_DATA = {
  sprint1: [
    {
      id: 1,
      name: "Maxim",
      avatar: avatar,
      date: "16 мая 2026",
      tgLink: "@maxic",
      mentorRating: 30,
      likes: 8,
      rate: 2,
    },
    {
      id: 2,
      name: "Vlas",
      avatar: avatar,
      date: "3 мая 2026",
      tgLink: "@Vlas",
      mentorRating: 50,
      likes: 1,
      rate: 1, // ✅ единственный с rate:1 в sprint1
    },
    {
      id: 3,
      name: "John",
      avatar: avatar,
      date: "7 мая 2026",
      tgLink: "@john",
      mentorRating: 35,
      likes: 1,
      rate: 32,
    },
    {
      id: 4,
      name: "Alice",
      avatar: avatar,
      date: "10 мая 2026",
      tgLink: "@alice",
      mentorRating: 42,
      likes: 3,
      rate: 5,
    },
    {
      id: 5,
      name: "Bob",
      avatar: avatar,
      date: "12 мая 2026",
      tgLink: "@bob",
      mentorRating: 28,
      likes: 2,
      rate: 7,
    },
    {
      id: 6,
      name: "Charlie",
      avatar: avatar,
      date: "14 мая 2026",
      tgLink: "@charlie",
      mentorRating: 55,
      likes: 4,
      rate: 3,
    },
    {
      id: 7,
      name: "Diana",
      avatar: avatar,
      date: "15 мая 2026",
      tgLink: "@diana",
      mentorRating: 48,
      likes: 6,
      rate: 4,
    },
    {
      id: 8,
      name: "Eve",
      avatar: avatar,
      date: "17 мая 2026",
      tgLink: "@eve",
      mentorRating: 33,
      likes: 2,
      rate: 6,
    },
    {
      id: 9,
      name: "Frank",
      avatar: avatar,
      date: "18 мая 2026",
      tgLink: "@frank",
      mentorRating: 41,
      likes: 5,
      rate: 8,
    },
    {
      id: 10,
      name: "Grace",
      avatar: avatar,
      date: "19 мая 2026",
      tgLink: "@grace",
      mentorRating: 37,
      likes: 3,
      rate: 9,
    },
  ],
  sprint2: [
    {
      id: 11,
      name: "Dan",
      avatar: avatar,
      date: "16 мая 2026",
      tgLink: "@mefex",
      mentorRating: 30,
      likes: 8,
      rate: 1, // ✅ единственный с rate:1 в sprint2
    },
    {
      id: 12,
      name: "Adam",
      avatar: avatar,
      date: "3 мая 2026",
      tgLink: "@adam",
      mentorRating: 50,
      likes: 1,
      rate: 3,
    },
    {
      id: 13,
      name: "Sophia",
      avatar: avatar,
      date: "5 мая 2026",
      tgLink: "@sophia",
      mentorRating: 44,
      likes: 2,
      rate: 4,
    },
    {
      id: 14,
      name: "Liam",
      avatar: avatar,
      date: "8 мая 2026",
      tgLink: "@liam",
      mentorRating: 38,
      likes: 3,
      rate: 5,
    },
    {
      id: 15,
      name: "Olivia",
      avatar: avatar,
      date: "11 мая 2026",
      tgLink: "@olivia",
      mentorRating: 52,
      likes: 5,
      rate: 2,
    },
    {
      id: 16,
      name: "Noah",
      avatar: avatar,
      date: "13 мая 2026",
      tgLink: "@noah",
      mentorRating: 29,
      likes: 1,
      rate: 6,
    },
    {
      id: 17,
      name: "Emma",
      avatar: avatar,
      date: "15 мая 2026",
      tgLink: "@emma",
      mentorRating: 47,
      likes: 4,
      rate: 7,
    },
    {
      id: 18,
      name: "Mason",
      avatar: avatar,
      date: "17 мая 2026",
      tgLink: "@mason",
      mentorRating: 36,
      likes: 2,
      rate: 8,
    },
    {
      id: 19,
      name: "Isabella",
      avatar: avatar,
      date: "19 мая 2026",
      tgLink: "@isabella",
      mentorRating: 43,
      likes: 3,
      rate: 9,
    },
    {
      id: 20,
      name: "Ethan",
      avatar: avatar,
      date: "20 мая 2026",
      tgLink: "@ethan",
      mentorRating: 39,
      likes: 2,
      rate: 10,
    },
  ],
  sprint3: [
    {
      id: 21,
      name: "mad_max",
      avatar: avatar,
      date: "1 мая 2026",
      tgLink: "@mad_max",
      mentorRating: 30,
      likes: 8,
      rate: 1, // ✅ единственный с rate:1 в sprint3
    },
    {
      id: 22,
      name: "Peter",
      avatar: avatar,
      date: "12 мая 2026",
      tgLink: "@j_Pter",
      mentorRating: 79,
      likes: 1,
      rate: 2,
    },
    {
      id: 23,
      name: "Mia",
      avatar: avatar,
      date: "4 мая 2026",
      tgLink: "@mia",
      mentorRating: 41,
      likes: 3,
      rate: 3,
    },
    {
      id: 24,
      name: "James",
      avatar: avatar,
      date: "6 мая 2026",
      tgLink: "@james",
      mentorRating: 34,
      likes: 2,
      rate: 4,
    },
    {
      id: 25,
      name: "Amelia",
      avatar: avatar,
      date: "9 мая 2026",
      tgLink: "@amelia",
      mentorRating: 56,
      likes: 6,
      rate: 5,
    },
    {
      id: 26,
      name: "Benjamin",
      avatar: avatar,
      date: "11 мая 2026",
      tgLink: "@benjamin",
      mentorRating: 45,
      likes: 3,
      rate: 6,
    },
    {
      id: 27,
      name: "Charlotte",
      avatar: avatar,
      date: "14 мая 2026",
      tgLink: "@charlotte",
      mentorRating: 38,
      likes: 4,
      rate: 7,
    },
    {
      id: 28,
      name: "Lucas",
      avatar: avatar,
      date: "16 мая 2026",
      tgLink: "@lucas",
      mentorRating: 42,
      likes: 2,
      rate: 8,
    },
    {
      id: 29,
      name: "Evelyn",
      avatar: avatar,
      date: "18 мая 2026",
      tgLink: "@evelyn",
      mentorRating: 49,
      likes: 5,
      rate: 9,
    },
    {
      id: 30,
      name: "Alexander",
      avatar: avatar,
      date: "20 мая 2026",
      tgLink: "@alex",
      mentorRating: 53,
      likes: 4,
      rate: 10,
    },
  ],
};

export const TECHNOLOGIES = [
  ["HTML", "CSS", "JavaScript"], // 3
  ["React", "TypeScript", "GO", "c++", "Python", "Rust", "WebAssembly"], // 2
  ["Vue", "Pinia", "Vite", "Nuxt.js"], // 4
  ["Node.js", "Express", "MongoDB", "Redis"], // 4
  ["Python", "Django"], // 2
  ["GO", "c++", "Python", "Rust", "WebAssembly"], // 5
  ["HTML", "CSS"], // 2
  ["Next.js", "React", "GO", "c++", "Python", "Rust", "WebAssembly"], // 2
  ["Docker", "Kubernetes", "AWS", "Terraform"], // 4
  ["GraphQL", "Apollo"], // 2
  ["Flutter", "Dart", "Firebase", "iOS", "Android"], // 5
];

export const sprintsDescription = {
  sprint1: [
    { text: "Главное — соответствие макету. Чем точнее, тем выше оценка наставника.", highlights: ["соответствие макету"] },
    { text: "Весь независимый от бэка JS-функционал должен работать: модалки, таймер, табы, формы и т.д.", highlights: ["работать"] },
    { text: "Все запросы к серверу — через мок-API (заглушки).", highlights: ["через мок-API"] },
    { text: "Кроссбраузерная совместимость: проект должен корректно отображаться в последних версиях Chrome, Firefox и Safari.", highlights: ["корректно отображаться"] },
  ],
  sprint2: [
    { text: "Обязательно адаптивная вёрстка для мобильных и десктопных устройств.", highlights: ["адаптивная вёрстка"] },
    { text: "Используй подход Mobile First при написании CSS-стилей.", highlights: ["Mobile First"] },
    { text: "Проверь работу интерфейса на экранах с разной шириной (от 320px до 1920px).", highlights: ["тестирование верстки"] },
  ],
  sprint3: [
    { text: "Код должен быть чистым, с комментариями и соблюдением code style.", highlights: ["чистый код", "комментарии", "code style"] },
    { text: "Используй понятные и семантичные имена для переменных и функций (self-documenting code).", highlights: ["семантика", "имена переменных"] },
    { text: "Избегай дублирования кода (DRY), выделяй переиспользуемые функции.", highlights: ["DRY", "переиспользование"] },
  ],
  sprint4: [
    { text: "Проверь корректность работы всех форм и валидации на клиенте.", highlights: ["форм и валидации"] },
    { text: "Реализуй cв реальном времени с выводом подсказок об ошибках.", highlights: ["Используй современные подходы"] },
    { text: "Обеспечь защиту от отправки пустых или некорректных данных на сервер.", highlights: ["защита данных", "безопасность форм"] },
  ],
  sprint5: [
    { text: "Используй современные подходы: хуки, Composition API, функциональные компоненты.", highlights: ["Используй современные подходы"] },
    { text: "Разделяй компоненты на Presentational (глупые) и Container (умные) для лучшей архитектуры.", highlights: ["Разделяй компоненты"] },
    { text: "Избегай использования классовых компонентов там, где можно обойтись функциональными.", highlights: ["классовых компонентов"] },
  ],
  sprint6: [
    { text: "Оптимизация производительности: lazy loading изображений и компонентов.", highlights: ["оптимизация", "lazy loading"] },
    { text: "Используй мемоизацию для тяжелых вычислений и рендера компонентов (React.memo, useMemo).", highlights: ["мемоизацию", "производительность"] },
    { text: "Минимизируй количество перерисовок (re-renders) дерева компонентов.", highlights: ["Минимизируй"] },
  ],
  sprint7: [
    { text: "Все стили должны быть инкапсулированы (CSS Modules или аналоги).", highlights: ["инкапсулированы"] },
    { text: "Не используй глобальные стили для компонентов, чтобы избежать конфликтов.", highlights: ["CSS Modules", "глобальные стили"] },
    { text: "Стили должны быть привязаны к компоненту и не влиять на другие части приложения.", highlights: ["модульность CSS"] },
  ],
  sprint9: [
    { text: "Реализуй доступность (a11y) для всех интерактивных элементов.", highlights: ["доступность", "a11y"] },
    { text: "Проверь навигацию с клавиатуры (Tab, Enter, Space) и корректную работу скринридеров.", highlights: ["клавиатурная навигация", "скринридеры"] },
    { text: "Используй семантические теги HTML5 (header, nav, main) для правильной структуры документа.", highlights: ["семантика HTML5", "a11y"] },
  ],
  sprint10: [
    { text: "Используй линтер и форматтер кода для автоматической проверки.", highlights: ["линтер", "форматтер"] },
    { text: "Настрой автоматический запуск линтера перед коммитом с помощью Husky.", highlights: ["Husky", "CI/CD"] },
    { text: "Соблюдай единый стиль кода во всем проекте без исключений.", highlights: ["code style", "стандартизация"] },
  ],
};

